-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity radix2_R1_V1 is
port (
    Ar : IN STD_LOGIC_VECTOR (15 downto 0);
    Ai : IN STD_LOGIC_VECTOR (15 downto 0);
    Br : IN STD_LOGIC_VECTOR (15 downto 0);
    Bi : IN STD_LOGIC_VECTOR (15 downto 0);
    Wr : IN STD_LOGIC_VECTOR (15 downto 0);
    Wi : IN STD_LOGIC_VECTOR (15 downto 0);
    Cr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Dr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Ci : OUT STD_LOGIC_VECTOR (15 downto 0);
    Di : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of radix2_R1_V1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "radix2_R1_V1_radix2_R1_V1,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=13.136000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=92,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal Cr_out_fu_110_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_134_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal Dr_out_fu_116_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Ci_out_fu_122_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_145_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal Di_out_fu_128_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_156_p3 : STD_LOGIC_VECTOR (15 downto 0);

    component radix2_R1_V1_ama_addmul_sub_16s_16ns_16s_16ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component radix2_R1_V1_ama_submuladd_16ns_16s_16s_16ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component radix2_R1_V1_am_addmul_16s_16s_16s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    ama_addmul_sub_16s_16ns_16s_16ns_16_1_1_U1 : component radix2_R1_V1_ama_addmul_sub_16s_16ns_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wi,
        din1 => Wr,
        din2 => Br,
        din3 => grp_fu_156_p3,
        dout => grp_fu_134_p4);

    ama_submuladd_16ns_16s_16s_16ns_16_1_1_U2 : component radix2_R1_V1_ama_submuladd_16ns_16s_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wr,
        din1 => Wi,
        din2 => Bi,
        din3 => grp_fu_156_p3,
        dout => grp_fu_145_p4);

    am_addmul_16s_16s_16s_16_1_1_U3 : component radix2_R1_V1_am_addmul_16s_16s_16s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Bi,
        din1 => Br,
        din2 => Wi,
        dout => grp_fu_156_p3);




    Ci <= std_logic_vector(signed(Ci_out_fu_122_p0) + signed(Ai));
    Ci_out_fu_122_p0 <= grp_fu_145_p4;
    Cr <= std_logic_vector(signed(Cr_out_fu_110_p0) + signed(Ar));
    Cr_out_fu_110_p0 <= grp_fu_134_p4;
    Di <= std_logic_vector(unsigned(Ai) - unsigned(Di_out_fu_128_p1));
    Di_out_fu_128_p1 <= grp_fu_145_p4;
    Dr <= std_logic_vector(unsigned(Ar) - unsigned(Dr_out_fu_116_p1));
    Dr_out_fu_116_p1 <= grp_fu_134_p4;
end behav;
